export const forms = [
  {
    form_name: 'banner_01',
    message_success: 'Enviado com sucesso!',
    message_error: 'Ops!',
    button: 'SEND MESSAGE',
    privacy_policy_enabled: 0,
    privacy_policy_name: 'politica_privacidade',
    privacy_policy_value: 'Sim',
    privacy_policy_label: 'Aceita as Políticas de Privacidade?',
    captation: 'LP_FORM_COTACAO',
    title: 'Book Now!',
    fields: [
      {
        type: 'text',
        name: 'nome',
        label: 'Full Name',
        placeholder: 'Full Name',
        required: '1',
        mask: '',
        switched: '',
      },
      {
        type: 'email',
        name: 'email',
        label: 'Email',
        placeholder: 'Email',
        required: '1',
        mask: '',
        switched: '',
      },
      {
        type: 'text',
        name: 'pickupdate',
        label: 'Pick Up Date',
        placeholder: 'Pick Up Date',
        required: '1',
        mask: '',
        switched: '',
      },
      {
        type: 'text',
        name: 'passengers',
        label: '# of Passenger',
        placeholder: '# of Passenger',
        required: '1',
        mask: '',
        switched: '',
      },
      {
        type: 'dropdown',
        name: 'trip',
        label: 'Trip Type',
        placeholder: 'Trip Type',
        required: '1',
        mask: '',
        switched: '',
        options: [
          {
            value: 'test_drive',
            label: 'Test Drive',
          },
          {
            value: 'manutencao',
            label: 'Manutenção',
          },
          {
            value: 'pos_venda',
            label: 'Pós venda',
          },
        ],
      },
      {
        type: 'dropdown',
        name: 'vehicle',
        label: 'Vehicle Type',
        placeholder: 'Vehicle Type',
        required: '1',
        mask: '',
        switched: '',
        options: [
          {
            value: 'test_drive',
            label: 'Test Drive',
          },
          {
            value: 'manutencao',
            label: 'Manutenção',
          },
          {
            value: 'pos_venda',
            label: 'Pós venda',
          },
        ],
      },
      {
        type: 'textarea',
        name: 'mensagem',
        label: 'Mensagem',
        placeholder: 'Mensagem',
        required: '1',
        mask: '',
        switched: '',
      },
    ],
  },
  {
    form_name: 'detail_01',
    message_success: 'Enviado com sucesso!',
    message_error: 'Ops!',
    button: 'SEND MESSAGE',
    privacy_policy_enabled: 0,
    privacy_policy_name: 'politica_privacidade',
    privacy_policy_value: 'Sim',
    privacy_policy_label: 'Aceita as Políticas de Privacidade?',
    captation: 'LP_FORM_COTACAO_DETAIL',
    title: 'Book Now!',
    fields: [
      {
        type: 'text',
        name: 'nome',
        label: 'Nome',
        placeholder: 'Nome',
        required: '1',
        mask: '',
      },
      {
        type: 'text',
        name: 'email',
        label: 'Email',
        placeholder: 'Email',
        required: '1',
        mask: '',
      },
      {
        type: 'text',
        name: 'telefone',
        label: 'Telefone',
        placeholder: 'Telefone',
        required: '1',
        mask: '(00)0000-0000',
      },
      {
        type: 'dropdown',
        name: 'unidade',
        label: 'Loja',
        placeholder: 'Loja',
        required: '1',
        mask: '',
        options: [
          {
            value: '64165',
            label: 'Filial 01',
          },
          {
            value: '67166',
            label: 'Filial 02',
          },
        ],
      },
      {
        type: 'variable',
        name: 'modelo',
        label: 'Modelo',
        placeholder: 'Modelo',
        required: '1',
        mask: '',
        variable: 'vehicles_dealers_detail',
      },
      {
        type: 'textarea',
        name: 'mensagem',
        label: 'Mensagem',
        placeholder: 'Mensagem',
        required: '1',
        mask: '',
      },
    ],
  },
];
