export const data = {
  forms: {
    banner_01: {
      settings: {
        message_success: 'Enviado com sucesso!',
        message_error: 'Ops!',
        button: 'SEND MESSAGE',
        privacy_policy: {
          enabled: 0,
          name: 'politica_privacidade',
          value: 'Sim',
          label: 'Aceita as Políticas de Privacidade?',
        },
        captation: 'LP_FORM_COTACAO',
        name: 'Book Now!',
      },
      fields: [
        {
          type: 'text',
          name: 'nome',
          label: 'Full Name',
          placeholder: 'Full Name',
          required: '1',
          mask: '',
          switched: '',
        },
        {
          type: 'email',
          name: 'email',
          label: 'Email',
          placeholder: 'Email',
          required: '1',
          mask: '',
          switched: '',
        },
        {
          type: 'text',
          name: 'pickupdate',
          label: 'Pick Up Date',
          placeholder: 'Pick Up Date',
          required: '1',
          mask: '',
          switched: '',
        },
        {
          type: 'text',
          name: 'passengers',
          label: '# of Passenger',
          placeholder: '# of Passenger',
          required: '1',
          mask: '',
          switched: '',
        },
        {
          type: 'dropdown',
          name: 'trip',
          label: 'Trip Type',
          placeholder: 'Trip Type',
          required: '1',
          mask: '',
          switched: '',
          options: [
            {
              value: 'test_drive',
              label: 'Test Drive',
            },
            {
              value: 'manutencao',
              label: 'Manutenção',
            },
            {
              value: 'pos_venda',
              label: 'Pós venda',
            },
          ],
        },
        {
          type: 'dropdown',
          name: 'vehicle',
          label: 'Vehicle Type',
          placeholder: 'Vehicle Type',
          required: '1',
          mask: '',
          switched: '',
          options: [
            {
              value: 'test_drive',
              label: 'Test Drive',
            },
            {
              value: 'manutencao',
              label: 'Manutenção',
            },
            {
              value: 'pos_venda',
              label: 'Pós venda',
            },
          ],
        },
        {
          type: 'textarea',
          name: 'mensagem',
          label: 'Mensagem',
          placeholder: 'Mensagem',
          required: '1',
          mask: '',
          switched: '',
        },
      ],
    },
    detail_01: {
      settings: {
        message_success: 'Nice!',
        message_error: 'Urgh!',
        button: 'Enviar',
        privacy_policy: {
          enabled: '1',
          name: 'politica_privacidade',
          value: 'Sim',
          label: 'Aceita as Pol\u00edticas de Privacidade?',
        },
        captation: 'LP_FORM_COTACAO',
        name: 'Cota\u00e7\u00e3o',
      },
      fields: [
        {
          type: 'text',
          name: 'nome',
          label: 'Nome',
          placeholder: 'Nome',
          required: '1',
          mask: '',
        },
        {
          type: 'text',
          name: 'email',
          label: 'Email',
          placeholder: 'Email',
          required: '1',
          mask: '',
        },
        {
          type: 'text',
          name: 'telefone',
          label: 'Telefone',
          placeholder: 'Telefone',
          required: '1',
          mask: '(00)0000-0000',
        },
        {
          type: 'dropdown',
          name: 'unidade',
          label: 'Loja',
          placeholder: 'Loja',
          required: '1',
          mask: '',
          options: [
            {
              value: '64165',
              label: 'Filial 01',
            },
            {
              value: '67166',
              label: 'Filial 02',
            },
          ],
        },
        {
          type: 'variable',
          name: 'modelo',
          label: 'Modelo',
          placeholder: 'Modelo',
          required: '1',
          mask: '',
          variable: 'vehicles_dealers_detail',
        },
        {
          type: 'textarea',
          name: 'mensagem',
          label: 'Mensagem',
          placeholder: 'Mensagem',
          required: '1',
          mask: '',
        },
      ],
    },
    formWhats: {
      settings: {
        message_success: 'Certinho!',
        message_error: 'Ops!',
        button: 'ENVIAR',
        privacy_policy: {
          enabled: '1',
          name: 'politica_privacidade',
          value: 'Sim',
          label: 'Aceita as Políticas de Privacidade?',
        },
        captation: 'LP_FORM_WHATSAPP',
        name: 'Entre em contato pelo WhatsApp!',
      },
      fields: [
        {
          type: 'text',
          name: 'nome',
          label: 'Nome Completo',
          placeholder: '',
          required: '1',
          mask: '',
        },
        {
          type: 'text',
          name: 'telefone',
          label: 'Telefone',
          placeholder: '',
          required: '1',
          mask: '(00)0000-0000',
        },
        {
          type: 'dropdown',
          name: 'unidade',
          label: 'Unidade',
          placeholder: 'Selecione',
          required: '1',
          mask: '',
          options: [
            {
              value: '64165',
              label: 'Filial 01',
            },
            {
              value: '67166',
              label: 'Filial 02',
            },
          ],
        },
      ],
    },
    form_sms: {
      settings: {
        message_success: 'Certinho!',
        message_error: 'Ops!',
        button: 'Enviar',
        privacy_policy: {
          enabled: '1',
          name: 'politica_privacidade',
          value: 'Sim',
          label: 'Aceita as Políticas de Privacidade?',
        },
        captation: 'LP_FORM_SMS',
        name: 'Vamos conversar?<br><span>Informe os dados abaixo.</span>',
      },
      fields: [
        {
          type: 'text',
          name: 'nome',
          label: '',
          placeholder: 'Nome',
          required: '1',
          mask: '',
        },
        {
          type: 'email',
          name: 'E-mail',
          label: '',
          placeholder: 'E-mail',
          required: '1',
          mask: '',
        },
        {
          type: 'text',
          name: 'telefone',
          label: '',
          placeholder: 'Telefone',
          required: '1',
          mask: '(00)0000-0000',
        },
      ],
    },
  },
  types: ['banner_01', 'detail_01'],
};
